'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService3Soap")>  _
    Public Interface WebService3Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarAlumno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarAlumno() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarAlumno", ReplyAction:="*")>  _
        Function ListarAlumnoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AgregarAlumno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AgregarAlumno(ByVal codAlumno As String, ByVal apellidos As String, ByVal nombres As String, ByVal lugarNac As String, ByVal fechaNac As Date, ByVal codEscuela As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AgregarAlumno", ReplyAction:="*")>  _
        Function AgregarAlumnoAsync(ByVal codAlumno As String, ByVal apellidos As String, ByVal nombres As String, ByVal lugarNac As String, ByVal fechaNac As Date, ByVal codEscuela As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarAlumno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EliminarAlumno(ByVal codAlumno As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarAlumno", ReplyAction:="*")>  _
        Function EliminarAlumnoAsync(ByVal codAlumno As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActualizarAlumno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ActualizarAlumno(ByVal codAlumno As String, ByVal apellidos As String, ByVal nombres As String, ByVal lugarNac As String, ByVal fechaNac As Date, ByVal codEscuela As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActualizarAlumno", ReplyAction:="*")>  _
        Function ActualizarAlumnoAsync(ByVal codAlumno As String, ByVal apellidos As String, ByVal nombres As String, ByVal lugarNac As String, ByVal fechaNac As Date, ByVal codEscuela As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarAlumno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BuscarAlumno(ByVal texto As String, ByVal criterio As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarAlumno", ReplyAction:="*")>  _
        Function BuscarAlumnoAsync(ByVal texto As String, ByVal criterio As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService3SoapChannel
        Inherits ServiceReference1.WebService3Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService3SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService3Soap)
        Implements ServiceReference1.WebService3Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListarAlumno() As System.Data.DataSet Implements ServiceReference1.WebService3Soap.ListarAlumno
            Return MyBase.Channel.ListarAlumno
        End Function
        
        Public Function ListarAlumnoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService3Soap.ListarAlumnoAsync
            Return MyBase.Channel.ListarAlumnoAsync
        End Function
        
        Public Function AgregarAlumno(ByVal codAlumno As String, ByVal apellidos As String, ByVal nombres As String, ByVal lugarNac As String, ByVal fechaNac As Date, ByVal codEscuela As String) As String() Implements ServiceReference1.WebService3Soap.AgregarAlumno
            Return MyBase.Channel.AgregarAlumno(codAlumno, apellidos, nombres, lugarNac, fechaNac, codEscuela)
        End Function
        
        Public Function AgregarAlumnoAsync(ByVal codAlumno As String, ByVal apellidos As String, ByVal nombres As String, ByVal lugarNac As String, ByVal fechaNac As Date, ByVal codEscuela As String) As System.Threading.Tasks.Task(Of String()) Implements ServiceReference1.WebService3Soap.AgregarAlumnoAsync
            Return MyBase.Channel.AgregarAlumnoAsync(codAlumno, apellidos, nombres, lugarNac, fechaNac, codEscuela)
        End Function
        
        Public Function EliminarAlumno(ByVal codAlumno As String) As String() Implements ServiceReference1.WebService3Soap.EliminarAlumno
            Return MyBase.Channel.EliminarAlumno(codAlumno)
        End Function
        
        Public Function EliminarAlumnoAsync(ByVal codAlumno As String) As System.Threading.Tasks.Task(Of String()) Implements ServiceReference1.WebService3Soap.EliminarAlumnoAsync
            Return MyBase.Channel.EliminarAlumnoAsync(codAlumno)
        End Function
        
        Public Function ActualizarAlumno(ByVal codAlumno As String, ByVal apellidos As String, ByVal nombres As String, ByVal lugarNac As String, ByVal fechaNac As Date, ByVal codEscuela As String) As String() Implements ServiceReference1.WebService3Soap.ActualizarAlumno
            Return MyBase.Channel.ActualizarAlumno(codAlumno, apellidos, nombres, lugarNac, fechaNac, codEscuela)
        End Function
        
        Public Function ActualizarAlumnoAsync(ByVal codAlumno As String, ByVal apellidos As String, ByVal nombres As String, ByVal lugarNac As String, ByVal fechaNac As Date, ByVal codEscuela As String) As System.Threading.Tasks.Task(Of String()) Implements ServiceReference1.WebService3Soap.ActualizarAlumnoAsync
            Return MyBase.Channel.ActualizarAlumnoAsync(codAlumno, apellidos, nombres, lugarNac, fechaNac, codEscuela)
        End Function
        
        Public Function BuscarAlumno(ByVal texto As String, ByVal criterio As String) As System.Data.DataSet Implements ServiceReference1.WebService3Soap.BuscarAlumno
            Return MyBase.Channel.BuscarAlumno(texto, criterio)
        End Function
        
        Public Function BuscarAlumnoAsync(ByVal texto As String, ByVal criterio As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService3Soap.BuscarAlumnoAsync
            Return MyBase.Channel.BuscarAlumnoAsync(texto, criterio)
        End Function
    End Class
End Namespace
