//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService3Soap")]
    public interface WebService3Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarAlumno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAlumnoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] AgregarAlumno(string codAlumno, string apellidos, string nombres, string lugarNac, System.DateTime fechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAlumnoAsync(string codAlumno, string apellidos, string nombres, string lugarNac, System.DateTime fechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] EliminarAlumno(string codAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAlumnoAsync(string codAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ActualizarAlumno(string codAlumno, string apellidos, string nombres, string lugarNac, System.DateTime fechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAlumnoAsync(string codAlumno, string apellidos, string nombres, string lugarNac, System.DateTime fechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BuscarAlumno(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAlumnoAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService3SoapChannel : ClienteWeb.ServiceReference2.WebService3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService3SoapClient : System.ServiceModel.ClientBase<ClienteWeb.ServiceReference2.WebService3Soap>, ClienteWeb.ServiceReference2.WebService3Soap {
        
        public WebService3SoapClient() {
        }
        
        public WebService3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarAlumno() {
            return base.Channel.ListarAlumno();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAlumnoAsync() {
            return base.Channel.ListarAlumnoAsync();
        }
        
        public string[] AgregarAlumno(string codAlumno, string apellidos, string nombres, string lugarNac, System.DateTime fechaNac, string codEscuela) {
            return base.Channel.AgregarAlumno(codAlumno, apellidos, nombres, lugarNac, fechaNac, codEscuela);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAlumnoAsync(string codAlumno, string apellidos, string nombres, string lugarNac, System.DateTime fechaNac, string codEscuela) {
            return base.Channel.AgregarAlumnoAsync(codAlumno, apellidos, nombres, lugarNac, fechaNac, codEscuela);
        }
        
        public string[] EliminarAlumno(string codAlumno) {
            return base.Channel.EliminarAlumno(codAlumno);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAlumnoAsync(string codAlumno) {
            return base.Channel.EliminarAlumnoAsync(codAlumno);
        }
        
        public string[] ActualizarAlumno(string codAlumno, string apellidos, string nombres, string lugarNac, System.DateTime fechaNac, string codEscuela) {
            return base.Channel.ActualizarAlumno(codAlumno, apellidos, nombres, lugarNac, fechaNac, codEscuela);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAlumnoAsync(string codAlumno, string apellidos, string nombres, string lugarNac, System.DateTime fechaNac, string codEscuela) {
            return base.Channel.ActualizarAlumnoAsync(codAlumno, apellidos, nombres, lugarNac, fechaNac, codEscuela);
        }
        
        public System.Data.DataSet BuscarAlumno(string texto, string criterio) {
            return base.Channel.BuscarAlumno(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAlumnoAsync(string texto, string criterio) {
            return base.Channel.BuscarAlumnoAsync(texto, criterio);
        }
    }
}
